version: "3.8"
services:
  php-apache-environment:
    container_name: php-apache01
    build:
      context: ./phpDir
      dockerfile: Dockerfile
    depends_on:
      - db01
    volumes:
      - ./phpDir/src:/var/www/html/
    ports:
      - 8081:80
  db:
    platform: linux/x86_64
    container_name: db01
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: lionPass
      MYSQL_DATABASE: lionDB
      MYSQL_USER: lionUser
      MYSQL_PASSWORD: lionPass
    ports:
      - "9998:3306"
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - "9091:80"
    restart: always
    environment:
      PMA_HOST: db01
    depends_on:
      - db01
